# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

def capacitor_pods
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
end

target 'Plugin' do
  capacitor_pods
  pod 'YouTubePlayer', :git => 'https://github.com/abritopach/Swift-YouTube-Player.git', :commit => 'dea29c23cd2f91314177a31d193d5257bbc3b7f9'
  pod 'SVProgressHUD'
end

target 'PluginTests' do
  capacitor_pods
  pod 'YouTubePlayer', :git => 'https://github.com/abritopach/Swift-YouTube-Player.git', :commit => 'dea29c23cd2f91314177a31d193d5257bbc3b7f9'
  pod 'SVProgressHUD'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end